### ISSUE TITLE
merge E4S documentation into this repo

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#1]
It would be nice if e4s documentation can be merged into this repo https://github.com/E4S-Project/E4S-Project.github.io 
That way we can have e4s release published on the e4s website https://e4s-project.github.io/.

**Comment by wspear** [comment]
I've linked the e4s README.md in this repo to the e4s.io about page so that information is more readily available.

**Comment by shahzebsiddiqui** [comment]
I saw the commit https://github.com/E4S-Project/E4S-Project.github.io/commit/db1b43f8bd77d7d5680990b3b2ec6962af9c083d i think having a link to the main E4S project is good but it would help to document the E4S release in the docs.

I don't see any reason why E4S docs should be separate from https://github.com/E4S-Project/e4s initially this repo was meant to target E4S release for facility but we can make this repo the main E4S repo for all E4S activity.
