### ISSUE TITLE
[software]: py-h5py

### ISSUE THREAD

**Issue by ax3l** [E4S-Project/e4s#107]
### Name of Software

h5py

### Request Description

h5py is used in a many of Python workflows for data processing of HDF5 (ECP) files.

HDF5 is funded by ECP.
h5py is a community project with HDF5 members contributing to.

Repo: https://github.com/h5py/h5py/
Spack package: `py-h5py`

### Is there a Spack Package

Yes

### Is your project funded by ECP

Yes

### E4S Community Policy

- [X] I agree to follow the E4S Community Policy

**Comment by eugeneswalker** [comment]
Hi Ax3l, thank you for this. We will add `py-h5py` to our next release of E4S. In the meantime, I created this PR to begin building `py-h5py` as part of the E4S stack in Spack CI:
* https://github.com/spack/spack/pull/34914

**Comment by ax3l** [comment]
Thanks a lot! :sparkling_heart:

**Comment by eugeneswalker** [comment]
Are there any particular variants besides the defaults you would like turned on explicitly?

**Comment by eugeneswalker** [comment]
Closing this as resolved following merge of https://github.com/spack/spack/pull/34914. If in the future you decide we should have certain non-default variants set, please don't hesitate to let us know.

**Comment by ax3l** [comment]
Thanks @eugeneswalker!

Yes, with and without MPI might be ideal. Many post-processing scripts are serial or embarrassingly parallel.
