### ISSUE TITLE
[support]: libEnsemble default variants

### ISSUE THREAD

**Issue by ax3l** [E4S-Project/e4s#108]
### Name of Software

py-libensemble

### URL for Software

https://github.com/Libensemble/libensemble

### Contact Details

@shuds13

### HPC System

Perlmutter (NERSC), Summit (OLCF)

### Request Description

The ECP libEnsemble project is packaged in Spack with a few variants, most defaulting to off.

Currently, E4S ships `py-libensemble` quite vanilla, which is not very useful for us downstream users (ECP WarpX here :wave:). Can we please update for future E4S releases the spec to something like:
```yaml
- py-libensemble +mpi +nlopt
```

Maybe we also just want to turn on all options for deployment, depending on what @shuds13 suggests.
```
Variants:
    Name [Default]     When    Allowed values    Description
    ===============    ====    ==============    ======================

    deap [off]         --      on, off           Install with DEAP
    mpi [off]          --      on, off           Install with MPI
    mpmath [off]       --      on, off           Install with mpmath
    nlopt [off]        --      on, off           Install with nlopt
    petsc4py [off]     --      on, off           Install with petsc4py
    pyyaml [off]       --      on, off           Install with pyyaml
    scipy [off]        --      on, off           Install with scipy
    tasmanian [off]    --      on, off           Install with tasmanian
```

Thanks for considering :sparkles: 

### Relevant log output

```shell
N/A
```

### Reproduce Bug

```bash
N/A
```

**Comment by shuds13** [comment]
@ax3l I'm happy to turn on any/all options for e4s deployment.

**Comment by eugeneswalker** [comment]
Yes, let us turn on whatever variants you want. We will make sure to include those variants in the upcoming E4S 23.02. 

In the meantime, how does this look for what we build as part of the E4S stack in Spack's CI?
* https://github.com/spack/spack/pull/34915

**Comment by shuds13** [comment]
@eugeneswalker Yes, looks good to me.

**Comment by eugeneswalker** [comment]
Closing as resolved. At any point if you want the variants to be changed, let us know, and we will update it. Thank you.
