### ISSUE TITLE
[support]: pumi test failure on JLSE

### ISSUE THREAD

**Issue by koysean** [E4S-Project/e4s#109]
### Name of Software

pumi

### URL for Software

https://www.scorec.rpi.edu/pumi/

### Contact Details

skoyama@anl.gov

### HPC System

JLSE

### Request Description

Pumi test in e4s-testsuite does not pass on JLSE.

### Reproduce Bug

```bash
1.
2.
3.
...
```

**Comment by wspear** [comment]
We have addressed this issue both by adding a working test to the E4S Testsuite: https://github.com/E4S-Project/testsuite/commit/365dfc199f127263c17c6a6e1349ab0deb185fd3 and by reporting the issue to the relevant pumi PR which should fix the test definition in the pumi package: https://github.com/spack/spack/pull/32446#discussion_r1073947501
