### ISSUE TITLE
Remove packages not part of ECP for future E4S deployment

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#11]
@sameershende @maherou @eugeneswalker 

There are few packages that don't belong in ECP which are part of E4S 21.05. I don't expect we remove this from 21.05 release though i think we should fix this in future releases. Right now it's not clear to me if we have a single source of truth to determine if product is E4S or ECP product. There is a PR (https://github.com/spack/spack/pull/23382)  I am working on to add tags `ecp` and `e4s` so one can just do `spack list -t ecp` or `spack list -t e4s` so that we have a source of truth from spack.

There are few sources that I have been looking at for determining if product is E4S which includes 
- https://github.com/E4S-Project/e4s
- https://confluence.exascaleproject.org/display/HISD/SI+Build+and+Test+Dashboard
- https://e4s-project.github.io/DocPortal.html
- https://confluence.exascaleproject.org/display/1ST/ECP+ST+Product+Readiness

It is bit easier to point out which packages are `e4s` right now i am referring to this repo though it is much harder to find which ones are `ecp` since it is not clear what products are funded by ECP. The open source products like ones below were not mentioned in any of the confluence dashboard so I think we should remove these packages as it adds more work for us to build packages that have nothing to do with ECP.

List of packages that we can remove please check the box, leave box unchecked if it should remain in E4S 

- [ ] [globalarray](https://github.com/E4S-Project/e4s/blob/master/spack.yaml#L228)
- [ ] [gmp](https://github.com/E4S-Project/e4s/blob/master/spack.yaml#L229)
- [ ] [libquo](https://github.com/E4S-Project/e4s/blob/master/spack.yaml#L240)
- [ ] [libunwind](https://github.com/E4S-Project/e4s/blob/master/spack.yaml#L241)
- [ ] [loki](https://github.com/E4S-Project/e4s/blob/master/spack.yaml#L242)
- [ ] [mercury](https://github.com/E4S-Project/e4s/blob/master/spack.yaml#L243)
- [ ] [mpark-variant](https://github.com/E4S-Project/e4s/blob/master/spack.yaml#L246)
- [ ] [mpifileutils](https://github.com/E4S-Project/e4s/blob/master/spack.yaml#L247)
- [ ] [qt](https://github.com/E4S-Project/e4s/blob/master/spack.yaml#L267)
- [ ] [qwt](https://github.com/E4S-Project/e4s/blob/master/spack.yaml#L269)
- [ ] [py-*](https://github.com/E4S-Project/e4s/blob/master/spack.yaml#L261-L266) packages 
- [ ] [stc](https://github.com/E4S-Project/e4s/blob/master/spack.yaml#L275)

I think we should also remove packages that are deprecated like `adios` @ax3l. I have been looking at https://github.com/E4S-Project/e4s-ci-badges to see products that have not had active development in past year or so. For instance we have
- [Rempi](https://github.com/PRUNERS/ReMPI) hasn't been updated since Jan 2020
- [SyclParallelSTL](https://github.com/KhronosGroup/SyclParallelSTL) hasn't been updated since Sep 2018. 

Products that have ceased development should be removed from ECP. We would need to reach out to product teams for their input. 

There has been some discussion about ECP and E4S packages in the slack channel: https://exascaleproject.slack.com/archives/C026VJUS8CS/p1625190469043500

Feel free to close this issue, I wanted to point this out and see if someone from E4S will address this in future release.

**Comment by eugeneswalker** [comment]
I'm happy to adjust things as needed. I think the decision to remove packages needs to be made with input from Sameer, yourself, and others. Some of the packages which you mention for removal were added on direct request from @tgamblin and @sameershende.

**Comment by ax3l** [comment]
@shahzebsiddiqui `mpark-variant` is a dependency of openPMD-api is a dependency of ECP WarpX :)
