### ISSUE TITLE
[software]: boost+python

### ISSUE THREAD

**Issue by marius311** [E4S-Project/e4s#110]
### Request Description

E4S already has boost in it, but with boost being an interfacing library, I don't think its as useful as it could be without various extensions. I think boost+python+filesystem+iostreams+system is a decent minimal setup, perhaps more (at least, that seems to be enough to use it from Python for me). 

### Is there a Spack Package

Yes

### Is your project funded by ECP

No

### E4S Community Policy

- [X] I agree to follow the E4S Community Policy

**Comment by eugeneswalker** [comment]
Hi @marius311, I submitted a PR to ensure we have at least `boost +python +filesystem +iostreams +system` in future E4S deployments:
* https://github.com/spack/spack/pull/35180

What do you think?
