### ISSUE TITLE
[support]: slate - spack test failure

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#114]
### Name of Software

slate

### Contact Details

shahzebsiddiqui@lbl.gov

### HPC System

Perlmutter

### Request Description

spack is failing to find binary for mpi command which doesn't make sense. We dont have `mpirun` or `mpiexec` but we do have `srun` and that is the preferred way to launch jobs on Perlmutter. 
```
 ~/ spack load slate
 ~/ spack test run slate
==> Spack test aor57ccammp4onqje6lvbwmjnhy6kb36
==> Testing package slate-2021.05.02-eh6rahv
==> Error: AttributeError: 'NoneType' object has no attribute 'command'

/global/common/software/spackecp/perlmutter/e4s-22.05/78535/spack/var/spack/repos/builtin/packages/slate/package.py:107, in test:
        104            mpiexe_f = which('srun', 'mpirun', 'mpiexec', path=mpi_path)
        105            self.run_test(mpiexe_f.command, test_args,
        106                          purpose='SLATE smoke test')
  >>    107            make('clean')

See test log for details:
  /global/homes/s/siddiq90/.spack/test/aor57ccammp4onqje6lvbwmjnhy6kb36/slate-2021.05.02-eh6rahv-test-out.txt

======================== 1 failed, 0 passed of 1 specs =========================
==> Error: 1 test(s) in the suite failed.
```

### Reproduce Bug

```bash
1. `ml e4s/22.05`
2. `spack env activate -V gcc`
3. `spack load --first slate`
4. `spack test run slate`
```

**Comment by shahzebsiddiqui** [comment]
@kadir

**Comment by shahzebsiddiqui** [comment]
looping in @mgates3 and @G-Ragghianti according to spack packages they are listed as maintainers. Note we have Kadir from slate team writing a test for e4s/22.05 so we will most likely use that instead of `spack test run`. https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/131

**Comment by mgates3** [comment]
Unfortunately Kadir left for another job. We'll have to get someone else to take that over.

**Comment by G-Ragghianti** [comment]
YOu say that you have "srun" available, but the spack test is only looking in the bin directory of the MPI that the slate package was built against.  Some questions:

- Are you using an external dependency for the MPI? 
- What is your spec?
- What is in the bin directory for the MPI that is being used?  
- What is in the test log that is referenced in your error report?

**Comment by G-Ragghianti** [comment]
I see your other issue report, but I don't believe that it includes all the answers to my previous questions.

**Comment by shahzebsiddiqui** [comment]
@mgates3 oh no thanks for heads up I didn't know that. Yeah there is an open MR that explains why I didn't hear back.

**Comment by shahzebsiddiqui** [comment]
>  Are you using an external dependency for the MPI? 

Yes we are using `cray-mpich` as an external package

> What is your spec?

```
==> 1 installed package
-- cray-sles15-zen3 / gcc@11.2.0 --------------------------------
eh6rahv47eeaho5fpbspere34glaq7cj slate@2021.05.02~cuda~ipo+mpi+openmp~rocm+shared build_type=RelWithDebInfo
```

You can reproduce this by running the following on Perlmutter

```
ml e4s/22.05
spack env activate -V gcc
spack find -Lv slate
```

> What is in the bin directory for the MPI that is being used?

I guess the `bin` directory for cray-mpich is the following 

```
 ~/ which mpicc
/opt/cray/pe/mpich/8.1.22/ofi/gnu/9.1/bin/mpicc
```

> What is in the test log that is referenced in your error report?

Reproducing the test and error

```
 ~/ spack load slate
 ~/ spack test run slate
==> Spack test aor57ccammp4onqje6lvbwmjnhy6kb36
==> Testing package slate-2021.05.02-eh6rahv
==> Error: AttributeError: 'NoneType' object has no attribute 'command'

/global/common/software/spackecp/perlmutter/e4s-22.05/78535/spack/var/spack/repos/builtin/packages/slate/package.py:107, in test:
        104            mpiexe_f = which('srun', 'mpirun', 'mpiexec', path=mpi_path)
        105            self.run_test(mpiexe_f.command, test_args,
        106                          purpose='SLATE smoke test')
  >>    107            make('clean')

See test log for details:
  /global/homes/s/siddiq90/.spack/test/aor57ccammp4onqje6lvbwmjnhy6kb36/slate-2021.05.02-eh6rahv-test-out.txt

======================== 1 failed, 0 passed of 1 specs =========================
==> Error: 1 test(s) in the suite failed.
```

Error Log

```
 ~/ spack test results -l -- slate
==> Results for test suite 'aor57ccammp4onqje6lvbwmjnhy6kb36', spec matching 'slate':
==> test specs:
==>   slate-2021.05.02-eh6rahv FAILED
==> Testing package slate-2021.05.02-eh6rahv
==> [2023-02-01-17:16:09.784332] Installing /global/common/software/spackecp/perlmutter/e4s-22.05/78535/spack/opt/spack/cray-sles15-zen3/gcc-11.2.0/slate-2021.05.02-eh6rahv47eeaho5fpbspere34glaq7cj/.spack/test to /global/homes/s/siddiq90/.spack/test/aor57ccammp4onqje6lvbwmjnhy6kb36/slate-2021.05.02-eh6rahv/cache/slate
==> [2023-02-01-17:16:09.821389] test: cmake: expect command status in [0]
==> [2023-02-01-17:16:09.821903] '/global/common/software/spackecp/perlmutter/e4s-22.05/78535/spack/opt/spack/cray-sles15-zen3/gcc-11.2.0/cmake-3.23.1-p23fzuowp4yuitemelic7f65nwybthxd/bin/cmake' '-DCMAKE_PREFIX_PATH=/global/common/software/spackecp/perlmutter/e4s-22.05/78535/spack/opt/spack/cray-sles15-zen3/gcc-11.2.0/blaspp-2021.04.01-hr443sas5vpx7s46e2eixanhaba6xr27;/global/common/software/spackecp/perlmutter/e4s-22.05/78535/spack/opt/spack/cray-sles15-zen3/gcc-11.2.0/lapackpp-2021.04.00-jsh2p3hhpfx6bux4ikbrxolpckgpgvsx;/opt/cray/pe/mpich/8.1.22/ofi/gnu/9.1' '..'
-- The CXX compiler identification is GNU 11.2.0
-- Cray Programming Environment 2.7.19 CXX
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /global/common/software/spackecp/perlmutter/e4s-22.05/78535/spack/lib/spack/env/gcc/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MPI_CXX: /global/common/software/spackecp/perlmutter/e4s-22.05/78535/spack/lib/spack/env/gcc/g++ (found version "3.1")
-- Found MPI: TRUE (found version "3.1") found components: CXX
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Configuring done
-- Generating done
-- Build files have been written to: /global/u1/s/siddiq90/.spack/test/aor57ccammp4onqje6lvbwmjnhy6kb36/slate-2021.05.02-eh6rahv/cache/slate/examples/build
add_executable( ex01_matrix, ex01_matrix.cc )
add_executable( ex02_conversion, ex02_conversion.cc )
add_executable( ex03_submatrix, ex03_submatrix.cc )
add_executable( ex04_norm, ex04_norm.cc )
add_executable( ex05_blas, ex05_blas.cc )
add_executable( ex06_linear_system_lu, ex06_linear_system_lu.cc )
add_executable( ex07_linear_system_cholesky, ex07_linear_system_cholesky.cc )
add_executable( ex08_linear_system_indefinite, ex08_linear_system_indefinite.cc )
add_executable( ex09_least_squares, ex09_least_squares.cc )
add_executable( ex10_svd, ex10_svd.cc )
add_executable( ex11_hermitian_eig, ex11_hermitian_eig.cc )
add_executable( ex12_generalized_hermitian_eig, ex12_generalized_hermitian_eig.cc )
add_executable( ex13_non_uniform_block_size, ex13_non_uniform_block_size.cc )
PASSED
==> [2023-02-01-17:16:12.114658] 'make' '-j16'
[  3%] Building CXX object CMakeFiles/ex01_matrix.dir/ex01_matrix.cc.o
[  7%] Building CXX object CMakeFiles/ex02_conversion.dir/ex02_conversion.cc.o
[ 11%] Building CXX object CMakeFiles/ex03_submatrix.dir/ex03_submatrix.cc.o
[ 15%] Building CXX object CMakeFiles/ex04_norm.dir/ex04_norm.cc.o
[ 19%] Building CXX object CMakeFiles/ex06_linear_system_lu.dir/ex06_linear_system_lu.cc.o
[ 23%] Building CXX object CMakeFiles/ex09_least_squares.dir/ex09_least_squares.cc.o
[ 26%] Building CXX object CMakeFiles/ex05_blas.dir/ex05_blas.cc.o
[ 30%] Building CXX object CMakeFiles/ex08_linear_system_indefinite.dir/ex08_linear_system_indefinite.cc.o
[ 34%] Building CXX object CMakeFiles/ex07_linear_system_cholesky.dir/ex07_linear_system_cholesky.cc.o
[ 38%] Building CXX object CMakeFiles/ex13_non_uniform_block_size.dir/ex13_non_uniform_block_size.cc.o
[ 42%] Building CXX object CMakeFiles/ex10_svd.dir/ex10_svd.cc.o
[ 46%] Building CXX object CMakeFiles/ex12_generalized_hermitian_eig.dir/ex12_generalized_hermitian_eig.cc.o
[ 50%] Building CXX object CMakeFiles/ex11_hermitian_eig.dir/ex11_hermitian_eig.cc.o
[ 53%] Linking CXX executable ex03_submatrix
[ 57%] Linking CXX executable ex05_blas
[ 61%] Linking CXX executable ex08_linear_system_indefinite
[ 61%] Built target ex03_submatrix
[ 65%] Linking CXX executable ex10_svd
[ 65%] Built target ex05_blas
[ 65%] Built target ex08_linear_system_indefinite
[ 65%] Built target ex10_svd
[ 69%] Linking CXX executable ex02_conversion
[ 69%] Built target ex02_conversion
[ 73%] Linking CXX executable ex13_non_uniform_block_size
[ 76%] Linking CXX executable ex01_matrix
[ 80%] Linking CXX executable ex06_linear_system_lu
[ 84%] Linking CXX executable ex04_norm
[ 88%] Linking CXX executable ex11_hermitian_eig
[ 92%] Linking CXX executable ex09_least_squares
[ 96%] Linking CXX executable ex12_generalized_hermitian_eig
[100%] Linking CXX executable ex07_linear_system_cholesky
[100%] Built target ex13_non_uniform_block_size
[100%] Built target ex01_matrix
[100%] Built target ex06_linear_system_lu
[100%] Built target ex04_norm
[100%] Built target ex11_hermitian_eig
[100%] Built target ex09_least_squares
[100%] Built target ex12_generalized_hermitian_eig
[100%] Built target ex07_linear_system_cholesky

======================== 1 failed, 0 passed of 1 specs =========================
```

**Comment by G-Ragghianti** [comment]
I don't know what your mpi install looks like, so I also need to see what files are located in the mpi "bin" directory.

**Comment by wspear** [comment]
Using the full mpi library path as the path to the mpi executor isn't generally safe. Some environments put their mpirun/srun elsewhere. This is the case with perlmutter. srun is in /usr/bin and only the mpi libraries/compilers are in the mpi path.

We recently had to implement our own test for pumi in the e4s testsuite because this issue is still present in their spack test implementation (our recommended fix was submitted here: https://github.com/spack/spack/pull/32446#discussion_r1073644981 ) Basically we advise against trying to infer the full path to the mpi executor. If the right one isn't available in the run environment that's user error.

**Comment by G-Ragghianti** [comment]
@wspear I've never really understood how the smoke tests are expected to work.  This code was initially put in for e4s without sufficient explanation as to how it was expected for the test code build process to find the things it needs.  Those dependencies are obviously installed by spack, but they are not properly provided to the smoke test process in a way that would be expected if you were using the package as a user (e.g. "spack load package" would provide everything that is listed as a runtime dependency). There are a lot of hacks that have been put into place for various packages to find the things they need for the smoke tests (like storing the location of the cmake that was used).

For my use of the smoke tests, it isn't reasonable to just expect the user to have everything separately available in the environment.  We use the smoke tests within a CI for validation of all our packages, and such a policy would require us to know ahead of time exactly what every package needs for the smoke tests.  This information is already known by spack, so I feel like the runtime dependencies should be provided automatically to the smoke test process. Short of that, I think it is reasonable for the smoke test itself to try to find the MPI executor that was built by spack and to fall back to finding the executor in the user's PATH.

**Comment by eugeneswalker** [comment]
> ... Those dependencies are obviously installed by spack, but they are not properly provided to the smoke test process in a way that would be expected if you were using the package as a user (e.g. "spack load package" would provide everything that is listed as a runtime dependency). 
>
> ... it isn't reasonable to just expect the user to have everything separately available in the environment. ... This information is already known by spack, so I feel like the runtime dependencies should be provided automatically to the smoke test process...

For what it's worth, I agree completely. We are talking with Spack's core team right now to get this changed so that, at the minimum, the run dependencies are loaded prior to compile+run for standalone tests. From initial conversations, they are in agreement this needs to be changed. It is not reasonable to expect package developer/test maintainer to manually inject logic to add what Spack already knows about via `depends_on` directives. Let us pursue that avenue and not have you or other developers waste time hacking around loading dependencies in the spack test logic when this should, and likely will be shortly, handled by Spack via its existing knowledge of dependencies. What do you think?

**Comment by G-Ragghianti** [comment]
Yes, this would be fabulous.  Please include me as a beta tester of any new functionality along these lines.

**Comment by G-Ragghianti** [comment]
Would anyone like to test this PR before it is merged? https://github.com/spack/spack/pull/35448

**Comment by G-Ragghianti** [comment]
The fix for this has been merged into the develop branch.

**Comment by eugeneswalker** [comment]
> The fix for this has been merged into the develop branch.

We will run this test as part of our E4S 23.02 deployment on Perlmutter.
