### ISSUE TITLE
WarpX 23.06+: Multi-Dim Build

### ISSUE THREAD

**Issue by ax3l** [E4S-Project/e4s#130]
After https://github.com/spack/spack/pull/38303 is merged for `warpx@23.06:` and `py-warpx@23.06`, the variant `dims` becomes a multi-variant.

By default, all four options `1,2,rz,3` are enabled and only need a single build per target architecture.

**Comment by eugeneswalker** [comment]
Thank you for the notice. We will incorporate these changes into our environments going forward.

**Comment by ax3l** [comment]
Thank you, @eugeneswalker :tada: 

Was this merged? Cannot see a linked PR in the issue :)

**Comment by eugeneswalker** [comment]
Yes, it was merged! Thank you!
