### ISSUE TITLE
update CHANGELOG 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#131]
@eugeneswalker can you please update the [changelog](https://github.com/E4S-Project/e4s/blob/master/CHANGELOG.md) so we can see what are the differences. Can you please try to do this for every release it would help to know what are the new packages that got added in the release.

**Comment by eugeneswalker** [comment]
There are now release notes that include this. See https://github.com/E4S-Project/e4s/releases/tag/v23.08
