### ISSUE TITLE
E4S releases

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#133]
@eugeneswalker we dont have any releases for this project see  https://github.com/E4S-Project/e4s/releases to go back in time and see what was changed. We dont have even tags. I think we should create the tag going forward. We can still create the release based on commit or PR but i am not entirely sure what commit to use.

I guess we could look at the history for this https://github.com/E4S-Project/e4s/tree/master/environments and inspect for each directory creation and use that for the release since you are the one that provides the release so for instance this https://github.com/E4S-Project/e4s/commit/0f41b28da5bae05967129d57275f1c5bb876c156 commit was the first one for E4S 23.05 but you had several commits see https://github.com/E4S-Project/e4s/commits/master/environments/23.05

**Comment by eugeneswalker** [comment]
Yes, we can do a tag going forward if you think it is best. For what commit to use, please use the latest commit. But, if it is for Perlmutter, we have provided a Perlmutter tailored environment on the system, which has been built in its entirety using Cray externals, and we would recommend that it be used as a starting point for customization by you.

**Comment by shahzebsiddiqui** [comment]
Yes please let's try to make tags it will help alot to go back in history and see old versions even though we just release one or more spack.yaml
