### ISSUE TITLE
Add E4S Community Policy in VCS

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#21]
@sameershende @maherou @eugeneswalker @wspear 

We need copy of the E4S community policy in version control. Perhaps they should be part of this repo stored in some subdirectory if it needs multiple versions or single file located at root of repo. xsdk has its policies located in https://github.com/xsdk-project/xsdk-community-policies/tree/master/spack_variant_guidelines 

Right now our community policies are in https://e4s-project.github.io/policies.html and this is maintained by this HTML file https://github.com/E4S-Project/E4S-Project.github.io/blob/master/policies.html we should convert this to markdown and be able to see history of changes.

**Comment by maherou** [comment]
@shahzebsiddiqui: The existing policies are under version control and can be seen in a version history.  HTML is not much harder to read than Markdown (IMO).  Am I missing your point?

**Comment by wspear** [comment]
This already exists:  https://github.com/E4S-Project/e4s-policies/blob/main/e4s-policies-1.0.md

**Comment by shahzebsiddiqui** [comment]
Oh I didn't see that link @wspear shared. I was looking for a markdown file since we already have this I will close this issue.

It's bit hard reading the raw content of a html file with anchors as pose to reading a markdown file. Thanks for the clarification.

**Comment by maherou** [comment]
Yeah, I create the original website and forgot that it is mostly built using Jekyll with Markdown.

**Comment by shahzebsiddiqui** [comment]
On a unrelated note, id like to see E4S documentation be open to contribution from everyone if we want to broaden scope of E4S. 

Generally most open source tools using something like readthedocs, mkdocs to build documentation.

Writing HTML for documentation is outdated. I would like to add some changes to e4s docs based on recent changes to this repo but I can't do that in HTML context it just quite messy. I am only familiar with sphinx for documentation build. Is there interest in moving to something like readthedocs? I'd be happy to build a prototype
