### ISSUE TITLE
[support]: Visualizing Tau Trace Results with Jumpshot

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#35]
### Name of Software

tau

### Contact Details

hsin-yu.ko@cornell.edu

### HPC System

Cori

### Request Description

User is trying to use tau to profile MPI code to debug which processor is causing idle performance.  This is a user ticket at NERSC [INC0175660](https://nersc.servicenowservices.com/sp/?id=form&sys_id=53f13baf1b83349059b0dc6ce54bcb20&table=incident)

At first the user tried using the tau instance we installed in extra_modules which is manual install and I dont who performed this action. Then i recommended user to use tau from e4s/21.05 stack.

```
(tmp) siddiq90@cori04> module av tau

------------- /global/common/software/nersc/cle7/extra_modulefiles -------------
tau/2.28.2(default)
```

Here is the initial response from user in the ticket. 

___

Dear NERSC Admin,

We are trying to use tau for profiling the processor idling our MPI program. We had success compiling our program with tau (thanks to your previous help!) However, the converted slog2 failed to be opened by the jumpshot program (in the tau module) with the following error message (last line):

```
[~/CSCR/take/owen-2021-08-17/03_tau_analysis.tracing] 10:13:03 (jobs:0)
hsinyu@cori05 $ jumpshot tau.slog2
GUI_LIBDIR is set. GUI_LIBDIR = /usr/common/software/tau/2.28.2/hsw/intel/craycnl/lib
Java is version 11.0.10.
Starting the SLOG-2 Display Program .....
GLib-GIO-Message: Using the 'memory' GSettings backend. Your settings will not be saved or shared with other applications.
Jumpshot-4 setup file : /global/homes/h/hsinyu/.jumpshot4.conf
Initialize Parameters:
Y_AXIS_ROOT_LABEL = SLOG-2
INIT_SLOG2_LEVEL_READ = 4
AUTO_WINDOWS_LOCATION = true
SCREEN_HEIGHT_RATIO = 0.5
TIME_SCROLL_UNIT_RATIO = 0.01
Y_AXIS_ROOT_VISIBLE = true
ACTIVE_REFRESH = false
ROW_RESIZE_MODE = Row
BACKGROUND_COLOR = black
STATE_HEIGHT_FACTOR = 0.9
NESTING_HEIGHT_FACTOR = 0.8
ARROW_ANTIALIASING = default
MIN_WIDTH_TO_DRAG = 4
CLICK_RADIUS_TO_LINE = 3
LEFTCLICK_INSTANT_ZOOM = true
STATE_BORDER = ColorRaised
ARROW_HEAD_LENGTH = 10
ARROW_HEAD_WIDTH = 6
EVENT_BASE_WIDTH = 8
PREVIEW_STATE_DISPLAY = CumulativeExclusionRatio
PREVIEW_STATE_BORDER = ColorXOR
PREVIEW_STATE_BORDER_W = 3
PREVIEW_STATE_BORDER_H = 0
PREVIEW_STATE_LEGEND_H = 2
PREVIEW_ARROW_LOG_BASE = 5
SEARCH_ARROW_LENGTH = 20
SEARCH_FRAME_THICKNESS = 3
SEARCHED_OBJECT_ON_TOP = false
HISTOGRAM_ZERO_ORIGIN = true
SUMMARY_STATE_BORDER = ColorRaised
SUMMARY_ARROW_LOG_BASE = 5
LEGEND_PREVIEW_ORDER = true
LEGEND_TOPOLOGY_ORDER = true
```

The file block pointer to the Tree Directory is NOT initialized!, can't read it.

Could you please help us with this issue?

Some additional detail of what we did:
The profiling run (job id: 47966556) is located on Cori at:

/global/cscratch1/sd/hsinyu/take/owen-2021-08-17/03_tau_analysis.tracing

The tau even tracing were enabled using our tau compiled program with a line the the submission script:

```
export TAU_TRACE=1
```

We converted the tau trace files to jumpshot format (slog2) with:

```
module load tau
tau_treemerge.pl
tau2slog2 tau.trc tau.edf -o tau.slog2
```

Please let us know if you need any further information. Thank you so much!

Best,
Hsin-Yu

### Relevant log output

```shell
hsinyu@cori11 $ tau_treemerge.pl ; echo $?; tau2slog2 tau.trc tau.edf -o tau.slog2 ; echo $?
...
31604000 Records read. 99% converted
1521 enters: 0 exits: 0
Reached end of trace file.
java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
at java.base/java.util.TimSort.sort(TimSort.java:254)
at java.base/java.util.Arrays.sort(Arrays.java:1441)
at base.drawable.Shadow.writeObject(Shadow.java:477)
at logformat.slog2.BufForShadows.writeObject(BufForShadows.java:291)
at logformat.slog2.output.TreeNode.writeObject(TreeNode.java:259)
at logformat.slog2.output.OutputLog.writeTreeNode(OutputLog.java:126)
at logformat.slog2.output.TreeTrunk.flushToFile(TreeTrunk.java:160)
at edu.uoregon.tau.Tau2Slog2.main(Tau2Slog2.java:202)
Exception in thread "main" java.lang.NullPointerException
at logformat.slog2.LineIDMapList.writeObject(LineIDMapList.java:33)
at logformat.slog2.output.OutputLog.writeFilePart(OutputLog.java:163)
at logformat.slog2.output.OutputLog.writeLineIDMapList(OutputLog.java:192)
at edu.uoregon.tau.Tau2Slog2.main(Tau2Slog2.java:213)
1
```

### Reproduce Bug

```bash
1. module load e4s/21.05
2. spack load tau
```

**Comment by wspear** [comment]
After significant digging I haven't found the actual root of the problem, which seems to lie in the slog2 library rather than the TAU-side code. However the trouble is related to an issue described here:  https://stackoverflow.com/questions/11441666/java-error-comparison-method-violates-its-general-contract

Basically a more recent implementation of java's sorting algorithm is more strict and can fault on input that worked with the prior implementation. The fix I will be applying to TAU, described in that stackoverflow link, is to revert to the legacy sort implementation, which can be done without touching the slog2 library code via `System.setProperty("java.util.Arrays.useLegacyMergeSort", "true");` Another workaround is to use jdk6 or earlier.

I can't apply this change to the TAU installs on cori but it would be a matter of replacing the jar file with my rebuilt one.

This is the result of the merge on my local system, with only the 0 threads included: https://yu.nic.uoregon.edu/~wspear/cori-full-tau.slog2

Note, however, that the merged trace from this example would be extremely large and unwieldy to view over X. If you isolate the first 16 ranks and and merge and convert those it may be easier to look at, if that provides sufficient coverage of the application's behavior. The first 16 ranks can be merged with the cori-installed TAU without encountering this bug. I have provided such a trace here: http://yu.nic.uoregon.edu/~wspear/cori-16-tau.slog2

**Comment by wspear** [comment]
@shahzebsiddiqui  This fix will be in place in the upcoming tau-2.31 release. In the meantime you can update existing installs of tau by doing:
wget http://yu.nic.uoregon.edu/~wspear/tau2slog2.jar
cp ./tau2slog2.jar </path/to/tau2>/<arch>/lib

**Comment by kosinyj** [comment]
Hi @wspear,

Thank you so much for your help! Sorry that I was not able to get back to you earlier. I was asked by @shahzebsiddiqui to provide our email discussion to provide a bit more context (please find them in the PDF files below).

[TAU_slog2_error.pdf](https://github.com/E4S-Project/e4s/files/7490729/TAU_slog2_error.pdf)
[TAU_slog2_error_2.pdf](https://github.com/E4S-Project/e4s/files/7490728/TAU_slog2_error_2.pdf)

Thanks very much again for your help,
Hsin-Yu

**Comment by shahzebsiddiqui** [comment]
We have updated the jarfile for the installation root for tau. just to confirm this is the checksum we have that we downloaded 

```
siddiq90@dtn01> sha256sum /global/common/software/spackecp/e4s-21.05/software/cray-cnl7-haswell/intel-19.1.3.304/tau-2.30.1-otn7sw7po5it6n3koe7cvorxzvrykluj/lib/tau2slog2.jar
ced189f5c54f272b557c9b7523bb950295208fc445649cf4015775bad909e8e8  /global/common/software/spackecp/e4s-21.05/software/cray-cnl7-haswell/intel-19.1.3.304/tau-2.30.1-otn7sw7po5it6n3koe7cvorxzvrykluj/lib/tau2slog2.jar
```
