### ISSUE TITLE
next release of E4S (21.XY) with spack 0.16.0 or higher 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#4]
@eugeneswalker this is an official request so its tracked here. This is in response to https://gitlab.com/ecp-swd/issuetracking/-/issues/23. 

I would recommend E4S team to coordinate when Spack will cut next release, certainly we don't want to use 0.16.0 since its the first major release with new concretizer, `spack test`. I would like we wait till spack team fix any known bugs in their next release. 

Based on our discussion, we should have a spack commit on the release tag so if its 0.16.0 it will be commit [77d9acb0710238ca661fd7c450ce0bee1e471483 ](https://github.com/spack/spack/commit/77d9acb0710238ca661fd7c450ce0bee1e471483). 

One option that was discussed was that E4S team can cut a release of E4S products by building them at the facility instead of Univ of Oregon machine. To be fair, E4S can rotate between sites when building E4S stack, this will give facility and E4S team confidence which packages work for the E4S release.

**Comment by eugeneswalker** [comment]
The 21.02 release is associated with Spack tag `e4s-21.02`
