### ISSUE TITLE
[software]: RAPIDS

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#65]
### Name of Software

RAPIDS

### Contact Details

shahzebsiddiqui@lbl.gov

### Request Description

RAPIDS is a GPU Data Science toolkit from NVIDIA that can be useful for Data Scientist running on GPUs. There are several spack packages that are provided by RAPIDS. I am not sure if anyone from ECP directly works on this. It is maintained by NVIDIA but i figure some members of the HPC community would benefit from installing these packages from source via spack. I know they provide RAPIDS as a container https://catalog.ngc.nvidia.com/orgs/nvidia/teams/rapidsai/containers/rapidsai 

- https://spack.readthedocs.io/en/latest/package_list.html#libcuml
- https://spack.readthedocs.io/en/latest/package_list.html#libcudf
- https://spack.readthedocs.io/en/latest/package_list.html#libcumlprims
- https://spack.readthedocs.io/en/latest/package_list.html#librmm

### Is there a Spack Package

Yes

### Is your project funded by ECP

Unsure

### E4S Community Policy

- [X] I agree to follow the E4S Community Policy

**Comment by eugeneswalker** [comment]
I can begin an initial evaluation of `RAPIDS` for inclusion in E4S next week. Let us leave this issue open to track follow up on this request.

**Comment by eugeneswalker** [comment]
Hi Shahzeb, following up from last week, we have added the RAPIDS packages you identified to our release process and will work to include them in the next release of E4S.
