### ISSUE TITLE
[software]: tensorflow

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#66]
### Name of Software

tensorflow, https://www.tensorflow.org

### Contact Details

shahzebsiddiqui@lbl.gov

### Request Description

Hi E4S,

Can we add tensorflow to the E4S distribution. This package has been requested numerous times at NERSC especially for Perlmutter. The spack package details can be found at https://spack.readthedocs.io/en/latest/package_list.html#py-tensorflow

### Is there a Spack Package

Yes

### Is your project funded by ECP

Unsure

### E4S Community Policy

- [X] I agree to follow the E4S Community Policy

**Comment by eugeneswalker** [comment]
I can begin an initial evaluation of py-tensorflow for inclusion in E4S next week. We will try the builds in our various environments and identify any issues. Let us leave this issue open until then.

**Comment by eugeneswalker** [comment]
Hi Shahzeb, following up from last week, we have added `py-tensorflow` to our process and will work to include it in the next release of E4S.
