### ISSUE TITLE
Missing 22.05 environment YAML for general x86_64

### ISSUE THREAD

**Issue by chuckatkins** [E4S-Project/e4s#69]
The published environments for v22.05 in `environments/22.05` are for GPU builds with CUDA, ROCm, and DPC++.  Is a baseline environment YAML available for the CPU-only installations? Furthermore, is a docker image even available without any of the GPU stacks enabled?

**Comment by eugeneswalker** [comment]
> Is a baseline environment YAML available for the CPU-only installations?

There is not. The CPU only install would be the same as the CUDA or ROCm environment, minus the ROCm specs, which are clearly labeled in the environment. You would just delete those lines. The package preferences and compiler definitions would remain the same.

> Furthermore, is a docker image even available without any of the GPU stacks enabled?

Yes, the Docker container image we used for our containerized builds was:
* `ecpe4s/ubuntu20.04-runner-x86_64:2022-05-01` 
* https://hub.docker.com/repository/docker/ecpe4s/ubuntu20.04-runner-x86_64/tags?page=1&ordering=last_updated

This image has GCC 9.4.0, has no GPU stack pre-installed, and is what we use for our containerized builds.

**Comment by eugeneswalker** [comment]
> The published environments for v22.05 in `environments/22.05` are for GPU builds with CUDA, ROCm, and DPC++. Is a baseline environment YAML available for the CPU-only installations? Furthermore, is a docker image even available without any of the GPU stacks enabled?
> > Is a baseline environment YAML available for the CPU-only installations?
> 
> There is not. The CPU only install would be the same as the CUDA or ROCm environment, minus the ROCm specs, which are clearly labeled in the environment. You would just delete those lines. The package preferences and compiler definitions would remain the same.

For instance, taking `22.05/cuda-x86_64.spack.yaml`:
* [CPU-only specs are listed lines 92-204](https://github.com/E4S-Project/e4s/blob/master/environments/22.05/cuda-x86_64.spack.yaml#L92-L204)

**Comment by eugeneswalker** [comment]
Closing this per follow up with @chuckatkins via Slack.
