### ISSUE TITLE
E4S Slack Channel - Open to Public

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#70]
@maherou @sameershende 

We have a E4S slack https://e4s-project.slack.com but its not open to public. I would recommend we open this to public so we can allow anyone to join the E4S community to ask for support, foster community and even use it for tutorials. 

I would recommend using something like [heroku](https://www.heroku.com/) to auto invite.  According to slack article https://slack.com/help/articles/115004856503-Manage-how-people-join-your-workspace one needs invite you can also set by domain to auto-invite folks. In the case of heroku its a self invite where one can just register without having to contact maintainer for approval. 

Here is an example of heroku app for buildtest that does slack invite https://hpcbuildtest.herokuapp.com/. You can also look at spack with their auto-invite to their slack https://slack.spack.io/ 

Once this is enabled we can update our user documentation and README.

**Comment by maherou** [comment]
@shahzebsiddiqui : I am open to whatever makes sense.

**Comment by nchaimov** [comment]
@shahzebsiddiqui I believe that the Google sign-in is also only for established accounts already invited, so we would need a system for automated invites whether or not Google SSO is used.

The invite page deployed on Heroku mentioned above seems to be based on https://github.com/outsideris/slack-invite-automation. Spack's auto-invite system is based on https://github.com/emedvedev/slackin-extended.

**Comment by shahzebsiddiqui** [comment]
I'll let one you setup heroku. Need someone with slack admin to do this see https://e4s-project.slack.com/archives/C032A9UAKT9/p1654898844371959?thread_ts=1654898844.371959&cid=C032A9UAKT9

**Comment by eugeneswalker** [comment]
> I'll let one you setup heroku. Need someone with slack admin to do this see https://e4s-project.slack.com/archives/C032A9UAKT9/p1654898844371959?thread_ts=1654898844.371959&cid=C032A9UAKT9

Can you confirm whether the approval went through?

**Comment by eugeneswalker** [comment]
From our conversations on E4S Slack, it looks like we are not able to integrate with the Slack auto-invite app:
* https://github.com/outsideris/slack-invite-automation

... because e4s-project.slack.com is not an Enterprise level account. 

We posted an issue with the outsideris GitHub repo requesting clarification as to whether this is a hard requirement:
* https://github.com/outsideris/slack-invite-automation/issues/151

**Comment by maherou** [comment]
Thanks, @eugeneswalker.  If having an enterprise level account is a requirement, perhaps we can look at purchasing this level.

**Comment by nchaimov** [comment]
@maherou I don't think it makes sense to purchase an Enterprise account for a support channel. Slack accounts are charged at roughly $15 per active user per month. Allowing public signups on an Enterprise account would essentially require us to pay $15 per month for every user who joins, committing ourselves to an arbitrarily high monthly fee. I believe that we have settled on the solution of whitelisting certain domain names so that users affiliated with national labs can invite themselves. 

If it is truly necessary to have a publicly-available chat service, given the high cost of Slack I think it would make more sense to transition to a different chat service, e.g, Zulip which offers access to an invitation API for free for open source projects: https://zulip.com/for/open-source/

**Comment by nchaimov** [comment]
We have whitelisted the following domains. People with e-mail addresses at these domains should now be able to automatically join the E4S sever.

- anl.gov
- lanl.gov
- llnl.gov
- uoregon.edu
- sandia.gov
- ornl.gov
- nersc.gov

**Comment by shahzebsiddiqui** [comment]
Right now would be the good time to explore other chat services since we have yet to officially announce slack as the primary communications and we  only have 10+ in slack.

Zulip looks promising considering it can also mirror slack chat. We can still keep the slack channel alive for time being. One thing that we have is the slack github notification for #e4s channel but I think we could do same with zulip assuming it works. I am all for exploring other chat services. 

I agree with Nick doesn't make sense to get enterprise slack it will increase cost dramatically over time and we may end up paying for users that may just join as one time user. 

Singularity community had recent change where they moved mattermost
 https://mattermost.com/?utm_source=google&utm_medium=cpc&utm_campaign=Google_Brand_NA&utm_term=mattermost&utm_placement=&gclid=CjwKCAjwqauVBhBGEiwAXOepkesvSzTUbkcZGHTAqa3OuerI9mY23C_-Qtxnty_DiMLdQicORhVXRRoCd5sQAvD_BwE

**Comment by shahzebsiddiqui** [comment]
You should remove .nersc.gov that is not used for emails that DNS is mostly for our servers

**Comment by eugeneswalker** [comment]
Since certain domains have been whitelisted, and auto-invite is not an option for us, should we close this issue?

**Comment by nchaimov** [comment]
We have whitelisted domains. I have also created a Zulip instance which we could use, which does support a self-invite system and non-expiring invitation links. I am not sure if any decision has been made as to what to use going forward.

**Comment by eugeneswalker** [comment]
> We have whitelisted domains. I have also created a Zulip instance which we could use, which does support a self-invite system and non-expiring invitation links. I am not sure if any decision has been made as to what to use going forward.

Should we close this now? The gist of this thread strikes me as a long term policy question. It sounds like Slack has been opened to the greatest extent possible, which was the original reason for this issue being created. And now, in addition to Spack having been opened up, Zulip is being explored as an alternative.

**Comment by shahzebsiddiqui** [comment]
haha so i am not the only one that has made this mistake `Slack` vs `Spack` , two completely different tools very easy to mistype

> And now, in addition to Spack having been opened up, Zulip is being explored as an alternative.

**Comment by eugeneswalker** [comment]
> haha so i am not the only one that has made this mistake `Slack` vs `Spack` , two completely different tools very easy to mistype
> 
> > And now, in addition to Spack having been opened up, Zulip is being explored as an alternative.

Haha! You know what, I think I actually wrote Slack when I first wrote that sentence, and actually changed it to Spack thinking I was correcting myself... Not good.

**Comment by shahzebsiddiqui** [comment]
I made this mistake a several times, so i am not the only one.
