### ISSUE TITLE
[software]: HDF5 Asynchronous I/O VOL Connector

### ISSUE THREAD

**Issue by houjun** [E4S-Project/e4s#77]
### Name of Software

HDF5 Asynchronous I/O VOL Connector, https://github.com/hpc-io/vol-async

### Contact Details

htang4@lbl.gov

### Request Description

Add HDF5 Asynchronous I/O VOL Connector, which enables HDF5 applications to perform asynchronous I/O operations.
[Code](https://github.com/hpc-io/vol-async)
[Spack package](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/hdf5-vol-async/package.py)
spack install hdf5-vol-async

Depends on HDF5 1.13+, Argobots, and MPI.

Would also be great if the next E4S release also include HDF5 1.13.1 (currently HDF5 version is up to 1.12.2)

### Is there a Spack Package

Yes

### Is your project funded by ECP

Yes

### E4S Community Policy

- [X] I agree to follow the E4S Community Policy

**Comment by sameershende** [comment]
I acknowledge this issue and we will work on integrating it in E4S.

**Comment by eugeneswalker** [comment]
Hi Houjun, I created a pull request to add:
1. `hdf5-vol-async` to our official development Spack environment used for CI testing:
   * https://github.com/spack/spack/pull/31747
2. Add `e4s` tag to the `hdf5-vol-async` Spack package

Once this PR merges, every PR to Spack will be required to not break the E4S build of `hdf5-vol-async`

**Comment by houjun** [comment]
> Hi Houjun, I created a pull request that:
> 
>     1. Adds `hdf5-vol-async` to our official development Spack environment used for CI testing:
>        
>        * [e4s ci stack: add spec: hdf5-vol-async spack/spack#31747](https://github.com/spack/spack/pull/31747)
> 
>     2. Add `e4s` tag to the `hdf5-vol-async` Spack package
> 
> 
> Once this PR merges, every subsequent PR to Spack will have the required of not breaking the E4S build of `hdf5-vol-async`

Great! Thanks very much!

**Comment by eugeneswalker** [comment]
The PR has been merged and `hdf5-vol-async` is now part of E4S develop environment for CI at Spack. It will be in E4S 22.08.
