### ISSUE TITLE
[docs]: Documentation on what type of issues to raise

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#78]
### Please describe the issue

I was contacted by [houjun](https://github.com/houjun) via slack on how to raise an issue to the E4S project. It would be better if we document what type of issues should be raised and what is not acceptable in terms of issue creation.

I can think of certain types of issues that is not acceptable and should be consulted via email or slack
1. Issue pertaining to change in E4S community policy
2. Issue pertaining to updating spack.yaml after release

**Comment by sameershende** [comment]
I acknowledge this issue. We will work on documenting what kind of issues should be raised.

**Comment by eugeneswalker** [comment]
For issues that should not be raised on this repo, what should we recommend to users? I can think of the following ways:
1. The e4s-project Slack space
2. The e4s channel on Spack's Slack space
3. Direct email communication

Are there other communication channels we should mention for those issues falling outside the scope of this repo's issue tracker?

**Comment by wspear** [comment]
I'm thinking this information should go in a new 'Support' section of the readthedocs documentation. That should probably include instructions for submitting issues, along with the types of issues supported here and examples of issues better reported through other channels.
