### ISSUE TITLE
e4s-21.02 reverted #5

### ISSUE THREAD

**Issue by sethrj** [E4S-Project/e4s#8]
Hi @eugeneswalker ,

I revisited the E4S spack file today while finalizing my upcoming ECP webinar, and it looks like 218ec1e2850b2bc0594f21864a36bf6e4f1ff00e reverted the changes from #5 : ForTrilinos is no longer being distributed with E4S, and the Fortran-enabled SWIG has been changed to the non-fortran version. Was this change intentional? Is there something I need to do to ensure the new packages and variant are distributed going forward? Thanks!

**Comment by eugeneswalker** [comment]
You should see Fortran-enabled swig in the spack.yaml at tag v21.02:

https://github.com/E4S-Project/e4s/blob/v21.02/spack.yaml#L181

For fortrilinos -- I don't know why that got removed. I just added it back to the E4S environments which are regularly built and monitored for failures on the Frank systems, and will do the same to this repo. See the link below for the precise environments being regularly built+monitored on Frank:
https://github.com/spack/spack-configs/tree/master/UOREGON/E4S-Develop

I'm glad you caught that, and apologize for not noticing it myself. Other than pointing it out as you did hear, I'm not sure what you could do :|

**Comment by eugeneswalker** [comment]
I'm just trying to concretize fortrilinos right now, using spack@develop, and I'm seeing a number of out-of-the-box concretization issues. How do you normally install fortrilinos with Spack? We should make sure that someone can actually do:

```
$> spack spec fortrilinos
```

and have that be OK right out of the box.

**Comment by eugeneswalker** [comment]
At least for now I can build it like this:

https://github.com/spack/spack-configs/commit/9b88baa773e294e3fcea8ff5f12300bed01d9a18

But it can be changed to whatever you and your team think is best for the purposes of maintaining it's buildability.

**Comment by eugeneswalker** [comment]
> Thanks for looking into thiss!

Absolutely. Thanks for bringing it to our attention.
