### ISSUE TITLE
[docs]: E4S Deployment on OLCF

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#82]
### Please describe the issue

We should document E4S deployment on OLCF in https://e4s.readthedocs.io/en/latest/deployment.html

According to https://dashboard.e4s.io/ we have multiple installation on Crusher.

**Comment by sameershende** [comment]
I acknowledge this issue. We will work on updating the documentation. There is still some discussion on our installation vs a system installation, but we can definitely describe what we have installed for 22.05 as shown in the dashboard.

**Comment by eugeneswalker** [comment]
Here is a PR adding the requested documentation:
* https://github.com/E4S-Project/e4s/pull/84
