### ISSUE TITLE
Visualize output of 'spack find' from facility deployment in E4S dashboard

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#92]
As we discussed in slack (https://e4s-project.slack.com/archives/C032A9UAKT9/p1660938038188749)  with @wspear, we publish the output of `spack find` in spack-configs repo such as https://github.com/spack/spack-configs/blob/main/NERSC/perlmutter/e4s-22.05/spack.yaml so that we can get this data visualized.

We can potentially put this in https://dashboard.e4s.io/ if the tooling is in place to visualize this. 

We need to decide on the format of these files so we can properly share this output with the E4S team. A few things are bit unclear to me

1. Should we place these `e4s-XX.YY.txt` files in https://github.com/spack/spack-configs or perhaps we put them in https://github.com/E4S-Project/e4s. If it's in spack-configs will E4S team just figure out the location where these files are or do they need to be put in this repo in a particular location
2. Decide on final output of `spack find` so we can properly share this information.
3. Potentially document this process in e4s.rtfd.io so other facilities that want to share this can contribute back with their `spack find` output.

**Comment by wspear** [comment]
I believe the dashboard is for tracking ParaTools deployments and isn't intended to handle other facility deployments. I think we're better off generating a table that can be embedded on an e4s.io page or in the readthedocs pages.

I think this generator command would work for me: `spack find -x --format "{name},{version},{compiler.name}@{compiler.version},{variants},{arch},{hash}"` That is assuming we only care about the explicitly installed packages (and the new PR to mark packages installed by metapackages as explicit gets in).

The current consumer for these find-output files, the docportal, just looks through a manually curated list of data file URL's. The locations in spack-configs aren't very consistent. I'm fine with keeping track of the files in spack-configs but certainly wouldn't object to having them moved to a more consistent (and more easily automated) location. On the other hand, I think it does make some sense to keep them adjacent to the spack environments that generated them for reference as is currently the case.

**Comment by shahzebsiddiqui** [comment]
@jfinney10 looping you in, we will update the output with the format as you suggested and contribute them back to the spack-configs repo in their desired location.

For time being, let's get an initial prototype and we can see how this data is visualized. I think this would help and we should get feedback from @sameershende @maherou, Katie and few others on how the tables will be represented.

I think the use of green, and red color to highlight table cell can make it easy to keep track of what get's installed that is if the specs are rows and columns are each site. If the table is one per system then it can done as well.

**Comment by shahzebsiddiqui** [comment]
I have updated the spack configuration for E4S 22.05 see https://github.com/spack/spack-configs/pull/52

**Comment by wspear** [comment]
So I have a prototype that generates markdown tables from the facility `spack find` output and I'm not sure that a single flat table is the way to go. hdf5 alone has over 300 rows (individual package installs) over all of the facility/system/version/etc combinations being tracked. This is from package lists created without the -x explicit flag so the number should be somewhat reduced when that is added. A sortable table with a search feature (probably implemented using DataTables javascript similar to the DocPortal) could also make it more manageable, but I want to make sure that's how we want to proceed before I present a full prototype thousands of rows long.

Possible alternatives (not mutually exclusive) include having separate tables for each product (DocPortal already somewhat provides this but a separate simplified resource could be provided) or separate tables for each facility, potentially subdivided by system before breaking down into the individual package installs.

**Comment by wspear** [comment]
Here is a prototype mega-table: http://yu.nic.uoregon.edu/~wspear/E4S/E4S-Project.github.io/Deployments.html
This contains all the products listed on the currently available deployment spack find documents for nearly 7000 entries.

**Comment by shahzebsiddiqui** [comment]
@wspear great work i like this initial prototype though i do agree going through all 7000 entries over maybe 700 pages with 100 entries per page is bit annoying. 

Being able to sort columns is great that does help quite a bit.

**Comment by wspear** [comment]
Addressed by: https://e4s-project.github.io/Deployments.html
