### ISSUE TITLE
E4S Community Policy finalize location

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/e4s#94]
Based on our discussion looks like https://github.com/E4S-Project/e4s-policies is the E4S community policy according to @wspear  @sameershende we also have https://e4s-project.github.io/policies.html and https://e4s.readthedocs.io/en/latest/policy.html

Perhaps we should remove the E4S community policy page https://github.com/E4S-Project/e4s/blob/master/docs/policy.rst to avoid confusion and redundancy in the policy.

**Comment by eugeneswalker** [comment]
I will consult with Wyatt and Sameer and we can make the appropriate change.

**Comment by wspear** [comment]
Addressed by: https://github.com/E4S-Project/e4s/pull/99

**Comment by eugeneswalker** [comment]
> Addressed by: #99

Closing as resolved.
